### ISSUE TITLE
Initial plugin readiness

### ISSUE THREAD

**Issue by robfletcher** [spinnaker/keel#769]
Part of #633 

I want to break this up into multiple PRs so this issue will track them.

## To-do

- [ ] `keel-api` should contain everything a plugin implementor would need
  - [x] `DeliveryConfig` and `Environment`
  - [x] `Resource` and `ResourceSpec`
  - [x] `ResourceHandler`
  - [x] `Resolver`
  - [x] `TaskLauncher` without direct dependency on `keel-orca`, i.e. just as an interface
  - [ ] An equivalent abstraction for CloudDriver without relying directly on Retrofit
  - [x] `Constraint` (migrating sub-classes to be registered like resource types) and `ConstraintEvaluator`
- [x] `keel-api` should have no dependencies on anything beyond Kotlin (for now)
- [x] Everything in `keel-actuator` and `keel-plugin` should either be moved to `keel-api` or `keel-core`
- [ ] `keel-bakery-plugin`, `keel-ec2-plugin` and `keel-titus-plugin` should only depend on `keel-api` (this is likely to involve the most work)
- [x] Fix up package names in `keel-api` so they don't conflict with other modules

## Considerations / Assumptions

The main things to consider are keeping Jackson, Java-object-diff, and any other libraries (I think those are the main ones that are likely to need some refactoring to remove from the crucial places) out of `keel-api`. 
We can revisit whether it's worth the effort to make `keel-api` pure Java (in order to remove the Kotlin dependency) later.

I think the `Submitted*` types don't need to be in `keel-api` which simplifies things a little as they are most likely to use Jackson annotations.
